create table if not exists users
(
    id    bigint generated by default as identity primary key,
    email varchar(254) not null,
    name  varchar(250) not null,
    unique (email)
);

create table if not exists categories
(
    id   bigint generated by default as identity primary key,
    name varchar(50) not null,
    unique (name)
);


create table if not exists events
(
    id                 bigint generated by default as identity primary key,
    annotation         varchar(2000)               not null,
    category_id        bigint                      not null,
    confirmed_requests bigint,
    description        varchar(7000)               not null,
    event_date         timestamp WITHOUT TIME ZONE not null,
    created_on         timestamp WITHOUT TIME ZONE,
    published_on       timestamp WITHOUT TIME ZONE NOT NULL,
    initiator_id       bigint                      not null,
    location_lat       float                       not null,
    location_lon       float                       not null,
    paid               boolean                     not null,
    participant_limit  int                         not null,
    request_moderation boolean                     not null,
    title              varchar(120)                not null,
    state              varchar(20)                 not null,
    views              BIGINT,
    constraint fk_events_category_id
        foreign key (category_id)
            references categories (id),
    constraint fk_events_initiator_id
        foreign key (initiator_id)
            references users (id) ON DELETE CASCADE

);

create table if not exists requests
(
    id           bigint generated by default as identity primary key,
    created      timestamp WITHOUT TIME ZONE not null,
    event_id     bigint                      not null,
    requester_id bigint                      not null,
    status       varchar(20)                 not null,
    constraint fk_requests_event_id
        foreign key (event_id)
            references events (id) ON DELETE CASCADE,
    constraint fk_requests_requester_id
        foreign key (requester_id)
            references users (id) ON DELETE CASCADE

);

create table if not exists compilations
(
    id     bigint generated by default as identity primary key,
    pinned boolean     not null,
    title  varchar(50) not null,
    unique (title)
);
create table if not exists compilations_events
(
    id             bigint generated by default as identity primary key,
    event_id       bigint not null,
    compilation_id bigint not null,
    constraint fk_events_compilations_event_id
        foreign key (event_id)
            references events (id) ON DELETE CASCADE,
    constraint fk_events_compilations_compilation_id
        foreign key (compilation_id)
            references compilations (id) ON DELETE CASCADE,
    CONSTRAINT uq_compilation_event UNIQUE (compilation_id, event_id)
);
