CREATE TABLE IF NOT EXISTS stats (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app	VARCHAR(100),
    uri	VARCHAR(1000),
    ip	VARCHAR(15),
    time_stamp TIMESTAMP WITHOUT TIME ZONE
    );


